---
- name: install DNS
  apt:
    name="dnsmasq"
    state=installed

- name: configure DNS
  copy:
    content="server=/lxc/10.0.3.1"
    dest="/etc/dnsmasq.d/lxc-domain"
  notify:
  - restart DNS

- name: start DNS
  service:
    name="dnsmasq"
    state=started
    enabled=yes
