---
- name: install LXC
  apt:
    name="{{ item }}"
    state=installed
  with_items:
  - "lxc"

- name: configure LXC
  lineinfile:
    dest="{{ item.dest }}"
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    state=present
  with_items:
  - { dest: "/etc/default/lxc-net", regexp: "#?LXC_DOMAIN=.*", line: "LXC_DOMAIN=\"lxc\""}
  - { dest: "/etc/default/lxc-net", regexp: "#?LXC_DHCP_CONFILE=.*", line: "LXC_DHCP_CONFILE=/etc/lxc/dnsmasq.conf"}
  notify:
  - restart LXC

- name: copy lxc-dnsmasq-wildcard.sh
  copy:
    src="lxc-dnsmasq-wildcard.sh"
    dest="/usr/local/bin/lxc-dnsmasq-wildcard.sh"
    mode="u=rwx,g=rx,o=x"
    owner="lxc-dnsmasq"
    group="lxc-dnsmasq"

- name: configure DNS for LXC
  lineinfile:
    line="dhcp-script=/usr/local/bin/lxc-dnsmasq-wildcard.sh"
    dest="/etc/lxc/dnsmasq.conf"
    state=present
    create=yes
  notify:
  - restart DNS

- name: configure LXC
  template:
    src="etc_lxc_default.conf.j2"
    dest="/etc/lxc/default.conf"

- name: create drop-in folder for LXC service
  file:
    dest="/etc/systemd/system/lxc.service.d"
    state=directory

- name: add dnsmasq drop-in for LXC service
  template:
    src="etc_systemd_system_lxc.service.d_99-dnsmasq.conf.j2"
    dest="/etc/systemd/system/lxc.service.d/99-dnsmasq.conf"

- name: start LXC
  service:
    name="{{ item }}.service"
    state=started
    enabled=yes
  with_items:
  - "lxc"
  - "lxc-net"
