---
- name: install APT packages
  apt:
    name="{{ item }}"
    state=installed
  with_items: "{{ common_apt_packages }}"

# FIXME: dpkg-divert --local --divert /usr/bin/ack --rename --add /usr/bin/ack-grep

- name: install Python modules
  pip:
    name="{{ item }}"
    state=present
  with_items:
  - "httplib2"
